export type Role = "master" | "research" | "code" | "judge" | "repair";
export type Status = "queued" | "running" | "passed" | "failed" | "blocked";
export type Phase = "PLAN" | "SPAWN" | "EXECUTE" | "TEST" | "EVALUATE" | "LEARN" | "REPLAN" | "DONE";
export interface Limits { MAX_DEPTH: number; MAX_AGENTS: number; MAX_RUNTIME_MS: number; MAX_BUDGET_USD: number; }
export const DEFAULT_LIMITS: Limits = { MAX_DEPTH: 3, MAX_AGENTS: 12, MAX_RUNTIME_MS: 10_000, MAX_BUDGET_USD: 0.5 };
export interface EmpireAgent { id: string; parentId: string | null; generation: number; role: Role; objective: string; status: Status; result?: string; score?: number; startedAt: string; finishedAt?: string; }
export interface MemoryEntry { id: string; kind: "decision" | "failure" | "lesson" | "evaluation"; content: string; createdAt: string; }
export interface LogEntry { timestamp: string; level: "info" | "warn" | "error"; event: string; phase: Phase; agentId?: string; message: string; }
export interface EmpireState { runId: string; goal: string; phase: Phase; status: "idle" | "running" | "completed" | "failed"; agents: EmpireAgent[]; memory: MemoryEntry[]; logs: LogEntry[]; retries: number; budgetUsedUsd: number; updatedAt: string; limits: Limits; }
export interface StateStore { load(): Promise<EmpireState | null>; save(state: EmpireState): Promise<void>; }
const now = () => new Date().toISOString();
const id = (prefix: string, n: number) => `${prefix}-${n}-${Math.random().toString(36).slice(2, 7)}`;
export function createState(goal: string, limits: Partial<Limits> = {}): EmpireState { return { runId: `run-${Date.now()}`, goal, phase: "PLAN", status: "idle", agents: [], memory: [], logs: [], retries: 0, budgetUsedUsd: 0, updatedAt: now(), limits: { ...DEFAULT_LIMITS, ...limits } }; }
function remember(state: EmpireState, kind: MemoryEntry["kind"], content: string) { state.memory.push({ id: id("memory", state.memory.length + 1), kind, content, createdAt: now() }); }
function log(state: EmpireState, level: LogEntry["level"], event: string, message: string, agentId?: string) { const entry: LogEntry = { timestamp: now(), level, event, phase: state.phase, message, ...(agentId ? { agentId } : {}) }; state.logs.push(entry); console.log(JSON.stringify({ runId: state.runId, ...entry })); }
function spawn(state: EmpireState, role: Role, parentId: string | null, generation: number, objective: string) { if (generation > state.limits.MAX_DEPTH || state.agents.length >= state.limits.MAX_AGENTS) return null; const agent: EmpireAgent = { id: id(role, state.agents.length + 1), parentId, generation, role, objective, status: "queued", startedAt: now() }; state.agents.push(agent); log(state, "info", "agent.spawned", `Spawned ${role} generation ${generation}.`, agent.id); return agent; }
function runtimeGuard(state: EmpireState, startedAt: number, store: StateStore) { if (Date.now() - startedAt <= state.limits.MAX_RUNTIME_MS) return false; state.phase = "EVALUATE"; state.status = "failed"; remember(state, "failure", "Execution terminated by MAX_RUNTIME_MS."); log(state, "error", "run.timeout", "Execution terminated by MAX_RUNTIME_MS."); state.updatedAt = now(); void store.save(state); return true; }
export async function runCycle(store: StateStore, goal: string, options: { demoFailure?: boolean; limits?: Partial<Limits> } = {}) {
  const startedAt = Date.now(); const existing = await store.load(); const state = existing?.status === "running" ? existing : createState(goal, options.limits); state.status = "running"; state.phase = "PLAN"; state.updatedAt = now(); log(state, "info", "run.started", `Plan created for: ${goal}`); remember(state, "decision", `Plan created for: ${goal}`);
  if (runtimeGuard(state, startedAt, store)) return state;
  state.phase = "SPAWN"; const master = spawn(state, "master", null, 0, "Coordinate the organization and enforce limits."); if (!master) throw new Error("MAX_AGENTS prevents master creation"); for (const role of ["research", "code", "judge"] as Role[]) spawn(state, role, master.id, 1, `Deliver the ${role} capability for the goal.`); if (runtimeGuard(state, startedAt, store)) return state;
  state.phase = "EXECUTE"; for (const agent of state.agents) { if (runtimeGuard(state, startedAt, store)) return state; if (agent.status !== "queued") continue; agent.status = "running"; log(state, "info", "agent.started", `${agent.role} execution started.`, agent.id); state.budgetUsedUsd += 0.01; if (state.budgetUsedUsd > state.limits.MAX_BUDGET_USD) { agent.status = "blocked"; agent.result = "Blocked by MAX_BUDGET."; log(state, "warn", "agent.blocked", "Blocked by MAX_BUDGET.", agent.id); continue; } agent.status = "passed"; agent.result = `${agent.role} completed a bounded deterministic task.`; agent.finishedAt = now(); log(state, "info", "agent.completed", agent.result, agent.id); }
  state.phase = "TEST"; const codeAgent = state.agents.find((agent) => agent.role === "code"); if (options.demoFailure && codeAgent && state.retries === 0) { codeAgent.status = "failed"; codeAgent.result = "Test failure: generated implementation missed a required assertion."; log(state, "error", "test.failed", codeAgent.result, codeAgent.id); state.phase = "EVALUATE"; remember(state, "failure", "Code worker failed an assertion; a repair specialist is required."); state.phase = "LEARN"; remember(state, "lesson", "Future code workers must run the assertion suite before reporting success."); state.retries += 1; state.phase = "REPLAN"; const repair = spawn(state, "repair", codeAgent.parentId, 2, "Repair the failed code worker and rerun the test suite."); if (repair) { repair.status = "passed"; repair.result = "Repair applied; the previously failing assertion now passes."; repair.finishedAt = now(); log(state, "info", "agent.repaired", repair.result, repair.id); remember(state, "evaluation", "Repair agent fixed the failure and restored the test invariant."); } state.phase = "TEST"; }
  if (runtimeGuard(state, startedAt, store)) return state;
  state.phase = "EVALUATE"; const passed = state.agents.filter((agent) => agent.status === "passed").length; const failed = state.agents.filter((agent) => agent.status === "failed").length; const judge = state.agents.find((agent) => agent.role === "judge"); if (judge) { judge.score = failed ? 7 : 9; judge.result = `Judge score ${judge.score}/10; ${failed ? "failure recorded for repair" : "all bounded workers passed"}.`; } remember(state, "evaluation", `${passed} agents passed; ${failed} agents failed; retries=${state.retries}.`); state.phase = state.retries > 0 ? "REPLAN" : "LEARN"; remember(state, "lesson", "Operational learning is persisted as memory and evaluation, not model retraining."); state.phase = "DONE"; state.status = "completed"; state.updatedAt = now(); log(state, "info", "run.completed", `Run completed with ${state.agents.length} agents.`); await store.save(state); return state;
}
export class MemoryStore implements StateStore { private state: EmpireState | null = null; async load() { return this.state; } async save(state: EmpireState) { this.state = structuredClone(state); } }
